version: '3'
services:
  web1:
    image: nginx:stable-alpine
    ports:
      - "80"
    labels:
      kompose.service.type: LoadBalancer

  web2:
    image: 192.168.99.100:5000/k8s-demo:v1
    ports:
      - "80"
    labels:
      kompose.service.type: LoadBalancer

